// utils/puzzleTopics.js
// List available CSVs and map to topic info for ChooseTopic UI

export const puzzleCSVs = [
  {
    id: 'mixed',
    title: 'Mixed Puzzles',
    description: 'A variety of puzzles covering all aspects of chess.',
    icon: '🎲',
    difficulty: 'All Levels',
    file: null, // Special case: loads from all CSV files
  },
  {
    id: 'checkmate34',
    title: 'Checkmate in 3 and 4',
    description: 'Practice checkmate patterns in 3 or 4 moves.',
    icon: '♟️',
    difficulty: 'Intermediate',
    file: '/puzzles/checkmate34.csv',
  },
  {
    id: 'endgame',
    title: 'Checkmate in 1 and 2',
    description: 'Practice delivering checkmate in 1 or 2 moves.',
    icon: '♔',
    difficulty: 'Beginner',
    file: '/puzzles/endgame.csv',
  },
  {
    id: 'checkmate',
    title: 'Checkmate',
    description: 'Practice checkmate patterns in 1 to 5 moves.',
    icon: '👑',
    difficulty: 'Intermediate',
    file: '/puzzles/checkmate.csv',
  },
  {
    id: 'backrankf2f7',
    title: 'Back Rank Mate and Attacking f2 or f7',
    description: 'Master back rank mates and attacks on the f2/f7 squares.',
    icon: '♔',
    difficulty: 'Intermediate',
    file: '/puzzles/backrankf2f7.csv',
  },
  {
    id: 'forkpin',
    title: 'Fork and Pin',
    description: 'Master fork and pin tactics - attacking multiple pieces and immobilizing them.',
    icon: '🍴',
    difficulty: 'Intermediate',
    file: '/puzzles/forkpin.csv',
  },
  {
    id: 'discoveredattackandhangingpiece',
    title: 'Discovered Attack and Hanging Piece',
    description: 'Master discovered attacks and hanging piece tactics.',
    icon: '🔗',
    difficulty: 'Advanced',
    file: '/puzzles/discoveredhanging.csv',
  },
  {
    id: 'skewerandcapturethedefender',
    title: 'Skewer and Capture the Defender',
    description: 'Master skewer tactics and capturing the defender.',
    icon: '🛡️',
    difficulty: 'Intermediate',
    file: '/puzzles/askewer.csv',
  },
  {
    id: 'fork',
    title: 'Fork',
    description: 'Master fork tactics - attacking multiple pieces simultaneously.',
    icon: '🍴',
    difficulty: 'Intermediate',
    file: '/puzzles/fork.csv',
  },
  {
    id: 'pin',
    title: 'Pin',
    description: 'Master pin tactics - immobilizing pieces by attacking them.',
    icon: '📌',
    difficulty: 'Intermediate',
    file: '/puzzles/pin.csv',
  },
  {
    id: 'hanging',
    title: 'Hanging Piece',
    description: 'Master hanging piece tactics - capturing undefended pieces.',
    icon: '🎯',
    difficulty: 'Intermediate',
    file: '/puzzles/hanging.csv',
  },
  {
    id: 'f2f7',
    title: 'Attacking f2/f7',
    description: 'Master attacks on the f2 and f7 squares.',
    icon: '⚔️',
    difficulty: 'Intermediate',
    file: '/puzzles/f2f7.csv',
  },
  {
    id: 'discovered',
    title: 'Discovered Attack',
    description: 'Master discovered attack tactics.',
    icon: '🔍',
    difficulty: 'Advanced',
    file: '/puzzles/discovered.csv',
  },
  {
    id: 'backrank',
    title: 'Back Rank Mate',
    description: 'Master back rank mate patterns.',
    icon: '♔',
    difficulty: 'Intermediate',
    file: '/puzzles/backrank.csv',
  },
];
